# Generated by Django 5.1.7 on 2025-04-04 04:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAssessmentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.FloatField()),
                ('keywords', models.JSONField()),
                ('summary', models.TextField()),
                ('suggestions', models.TextField()),
                ('radar_scores', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.assessment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.team')),
            ],
            options={
                'unique_together': {('assessment', 'team')},
            },
        ),
    ]
