# Generated by Django 5.1.7 on 2025-04-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_teamassessmentanalysis_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenEndedToneAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_feedback', models.TextField()),
                ('rewritten_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.assessment')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tone_given', to='my_app.user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.assessmentquestion')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tone_received', to='my_app.user')),
            ],
            options={
                'unique_together': {('assessment', 'question', 'from_user', 'to_user')},
            },
        ),
    ]
